Repository marcpage/genweb, pull requests merged in 2024-08, with the labels that each got.

#3 Users/pagerk/starting again
  .github/workflows/CI.yml
  genweb/artifact_editor.py
  genweb/build_web_pages.py
  genweb/database.py
  genweb/generate_html.py
  genweb/metaphone.py
  genweb/rmagic.py
  genweb/storage.py
  genweb/table.py
  genweb/templates/alpha_toc.html.mako
  genweb/templates/person_index.html.mako
  pr_build.py
  requirements.txt
  tests/test_database.py
  tests/test_generate_html.py
  tests/test_metaphone.py
  tests/test_storage.py
  tests/test_table.py
Labels: Quality

#4 Infastructure added
  LICENSE
  Makefile
  genweb/__init__.py
  genweb/genweb.py
  pyproject.toml
Labels: documentation

#5 Users/marcp/xml cleanup
  genweb/parse_metadata.py
Labels: enhancement

#6 Add gedcom5 dependency
  pyproject.toml
Labels: documentation

#7 switch gedcom parser
  pyproject.toml
Labels: documentation

#9 Basic relationship loading
  Makefile
  genweb/relationships.py
  tests/data/555SAMPLE.GED
  tests/data/MINIMAL555.GED
  tests/data/README.md
  tests/data/REMARR.GED
  tests/data/SSMARR.GED
  tests/test_relationships.py
Labels: enhancement

#10 Add a People object that handles canoncial id to people
  Makefile
  README.md
  genweb/people.py
  tests/test_people.py
Labels: enhancement

#13 Adding template rendering
  Makefile
  README.md
  genweb/template.py
  tests/data/test.html.mako
  tests/data/test_include.html.mako
  tests/test_template.py
Labels: enhancement

#14 Increase test coverage to 90%
  Makefile
  README.md
  genweb/parse_metadata.py
  genweb/people.py
  genweb/relationships.py
  tests/data/test.xml
  tests/test_parse_metdata.py
  tests/test_people.py
  tests/test_relationships.py
Labels: enhancement

#15 starting work on individual web pages
  Makefile
  README.md
  genweb/genweb.py
  genweb/parse_metadata.py
  genweb/people.py
  genweb/relationships.py
  genweb/templates/person.html.mako
  tests/test_people.py
Labels: enhancement

#16 Prevent broken links
  genweb/genweb.py
  genweb/templates/nav_area.html.mako
  genweb/templates/person.html.mako
Labels: bug

#18 added style for navigation images
  genweb/templates/nav_area.html.mako
  genweb/templates/person.html.mako
Labels: enhancement

#19 created the top level index and added index from all person pages
  Makefile
  README.md
  genweb/genweb.py
  genweb/templates/person.html.mako
  genweb/templates/top_level.html.mako
Labels: enhancement

#24 Adding basic functionality for a webserver
  Makefile
  README.md
  genweb/webserver.py
Labels: enhancement

#28 Break up top-level index into surnames by letter
  genweb/templates/top_level.html.mako
Labels: enhancement

#30 added labels to nav area and no display for empty areas
  genweb/templates/nav_area.html.mako
  genweb/templates/person.html.mako
Labels: enhancement

#31 Added images to individual web pages
  genweb/genweb.py
  genweb/templates/person.html.mako
  tests/test_genweb.py
Labels: enhancement

#33 Added all images for each person, added personal image file to website
  genweb/genweb.py
  genweb/genweb.yml
  genweb/templates/nav_area.html.mako
  genweb/templates/person.html.mako
Labels: enhancement

#34 We now include .src files in the output
  genweb/data/styles.css
  genweb/parse_metadata.py
  genweb/templates/person.html.mako
  tests/test_genweb.py
Labels: enhancement

#38 Grouping items by year in person view
  genweb/templates/inline.html.mako
  genweb/templates/nav_area.html.mako
  genweb/templates/person.html.mako
  genweb/templates/picture.html.mako
  genweb/templates/top_level.html.mako
Labels: enhancement

#39 Increasing unit test code coverage to over 90%
  genweb/genweb.py
  genweb/parse_metadata.py
  tests/data/fake.jpg
  tests/data/fake2.jpg
  tests/test_genweb.py
  tests/test_parse_metdata.py
Labels: Quality

#40 added href support
  genweb/genweb.py
  genweb/templates/href.html.mako
  genweb/templates/person.html.mako
Labels: enhancement

#43 Add alias support
  genweb/genweb.py
  genweb/people.py
  tests/test_people.py
Labels: enhancement

#45 Updating the top level readme
  README.md
Labels: documentation

#55 Prevent Pedigree xml files from being parsed
  genweb/parse_metadata.py
Labels: Quality

#58 We can now save changes to metadata
  genweb/metadata.py
  tests/data/layered 2024-01-05.yml
  tests/data/layered.yml
  tests/test_metadata.py
Labels: enhancement

#60 Move js and css out into their own files
  genweb/data/editor.html
  genweb/data/editor.js
  genweb/data/styles.css
  genweb/webapi_v1.py
  genweb/webserver.py
Labels: Quality

#63 Calling `make format` will now update the code coverage number in `README.md`
  Makefile
  README.md
Labels: Quality

#64 Add unit tests for AWS
  genweb/aws.py
  tests/test_aws.py
Labels: Quality

#65 full test coverage of webapi_v1.py
  tests/test_webapi_v1.py
Labels: Quality

#66 Full test coverage on Metadata
  tests/test_metadata.py
Labels: Quality

#68 Sort children in nav area by age
  genweb/templates/person.html.mako
Labels: enhancement

#69 Adding links to originals
  genweb/cleanup.py
  genweb/metadata.py
  genweb/parse_metadata.py
  genweb/templates/picture.html.mako
  tests/data/example.yml
  tests/test_metadata.py
  tests/test_parse_metdata.py
Labels: enhancement

#71 Users/marcp/update web editor for inline references and picture originals
  genweb/data/editor.html
  genweb/data/editor.js
  genweb/webapi_v1.py
Labels: bug

#74 Add video player code for inline
  genweb/templates/person.html.mako
  genweb/templates/video.js
Labels: bug

#75 A few more things we can delete from the artifacts folder
  genweb/cleanup.py
Labels: Quality

#77 While updating tests found some dead code
  genweb/webapi_v1.py
  tests/test_webapi_v1.py
Labels: Quality

#78 Add ability to get file hashes from inventory
  genweb/inventory.py
  tests/test_inventory.py
Labels: enhancement

#79 Lookup up files by size or size and hash
  genweb/inventory.py
  tests/test_inventory.py
Labels: enhancement
